services:
  - type: web
    name: medassist-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "cd backend && pip install -r requirements-lite.txt"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: OFFLINE_MODE
        value: True
